---
# tasks file for local-ch
- name: create testdir in tmp
  file:
       path: /tmp/testdir
       state: directory
       owner: root
       group: root
       mode: 0755
  tags: create_dir
  

- name: create file1 in tmp/testdir
  file:
       path: /tmp/testdir/file1
       state: touch
       owner: root
       group: root
       mode: 0755
  tags: create_file